version: '3.8'
services:
  backend:
    build: ./backend
    container_name: backend-app
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend-app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
